name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Ou 'master', dependendo do nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Configura o "Agente SSH" e carrega sua chave OPENSSH na memória
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

  # 2. Adiciona o IP do servidor aos hosts conhecidos (para evitar perguntas de Sim/Não)
    - name: Add Remote to Known Hosts
      run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
  # 3. Executa os comandos via SSH nativo
    - name: Deploy Script
      run: | 
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          # Carrega NVM
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          
          # Entra na pasta
          cd ~/site-serde || exit 1
          
          # Comandos de deploy
          git pull origin main
          npm install
          # NODE_OPTIONS='--max-old-space-size=2048' 
          npm run build
          
          # Reinicia PM2
          pm2 restart serde
        EOF
